version: "3"
services:
  js:
    container_name: vast_player_js
    tty: true
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/root/vast_player_js
    command: bash -c "./docker-entrypoint.sh && bash"
